International phone number, no-browser documentation
undrfined/ivdiff pull request #3
Opened 2019-10-16 18:06 UTC by prettydude

2019-10-16 18:08 UTC, mkriventsev commented
@prettydude xD hoces futbolku?
#hacktoberfest

2019-10-16 18:55 UTC, prettydude commented
Нет, фикшу ivdiff за полгода после конкурса :D

2020-10-02 10:33 UTC, undrfined requested changes
Please fix all the suggested changes

2020-10-02 10:33 UTC, undrfined commented on README.md
> +To authenticate run script `auth.py` with your phone number that linked to Telegram:
```suggestion
To authenticate run script `auth.py` with your phone number that is linked to Telegram:
```

2020-10-02 10:33 UTC, undrfined commented on README.md
> +If you want not to open generated files, add `-n or --nobrowser`
```suggestion
If you don't want to open generated files, add `-n or --nobrowser`
```

2020-10-02 16:02 UTC, closed without merging